### ISSUE TITLE
Omniauth uses dispatch.Http without thread safety

### ISSUE THREAD

**Issue by joescii** [ghostm/lift-omniauth#47]
Our application in production began failing during OAuth requests this week.  The failure occurs where we are using `Omniauth.http` to get the token from the other server.  Granted this is occurring in a custom-built `Provider`, I suspect it could be an issue for _Omniauth_ usage in general.  I'm opening this as a ticket to get community feedback before making a move.

[In our source](https://github.com/ghostm/lift-omniauth/blob/master/src/main/scala/omniauth/Omniauth.scala#L40), we simply instantiate a `new Http` for handling our requests. The documentation for _dispatch_ [states clearly](http://dispatch-classic.databinder.net/Choose+an+Executor.html#Current+Thread+Blocking+%28dispatch-http%29) that a plain `new Http` is not thread-safe.  _Omniauth_ should either mix in `thread.Safety` or use the singleton `Http` object.

Below is the exception we see repeatedly:

```text
2015-01-09_22:17:43.262 [http-bio-8080-exec-336] ERROR net.liftweb.http.LiftRules - Exception being returned to browser when processing /auth/dk/callback
java.lang.IllegalStateException: Invalid use of SingleClientConnManager: connection still allocated.
Make sure to release the connection before allocating another one.
	at org.apache.http.impl.conn.SingleClientConnManager.getConnection(SingleClientConnManager.java:217) ~[httpclient-4.1.3.jar:4.1.3]
	at org.apache.http.impl.conn.SingleClientConnManager$1.getConnection(SingleClientConnManager.java:190) ~[httpclient-4.1.3.jar:4.1.3]
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:401) ~[httpclient-4.1.3.jar:4.1.3]
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820) ~[httpclient-4.1.3.jar:4.1.3]
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:776) ~[httpclient-4.1.3.jar:4.1.3]
	at dispatch.classic.BlockingHttp$class.dispatch$classic$BlockingHttp$$execute(Http.scala:45) ~[dispatch-http_2.10-0.8.10.jar:0.8.10]
	at dispatch.classic.BlockingHttp$$anonfun$execute$1$$anonfun$apply$3.apply(Http.scala:58) ~[dispatch-http_2.10-0.8.10.jar:0.8.10]
	at dispatch.classic.BlockingHttp$$anonfun$execute$1$$anonfun$apply$3.apply(Http.scala:58) ~[dispatch-http_2.10-0.8.10.jar:0.8.10]
	at scala.Option.getOrElse(Option.scala:120) ~[scala-library-2.10.4.jar:na]
	at dispatch.classic.BlockingHttp$$anonfun$execute$1.apply(Http.scala:58) ~[dispatch-http_2.10-0.8.10.jar:0.8.10]
	at dispatch.classic.Http.pack(Http.scala:25) ~[dispatch-http_2.10-0.8.10.jar:0.8.10]
	at dispatch.classic.BlockingHttp$class.execute(Http.scala:53) ~[dispatch-http_2.10-0.8.10.jar:0.8.10]
	at dispatch.classic.Http.execute(Http.scala:21) ~[dispatch-http_2.10-0.8.10.jar:0.8.10]
	at dispatch.classic.HttpExecutor$class.x(executor.scala:36) ~[dispatch-core_2.10-0.8.10.jar:0.8.10]
	at dispatch.classic.Http.x(Http.scala:21) ~[dispatch-http_2.10-0.8.10.jar:0.8.10]
	at dispatch.classic.HttpExecutor$class.when(executor.scala:50) ~[dispatch-core_2.10-0.8.10.jar:0.8.10]
	at dispatch.classic.Http.when(Http.scala:21) ~[dispatch-http_2.10-0.8.10.jar:0.8.10]
	at dispatch.classic.HttpExecutor$class.apply(executor.scala:60) ~[dispatch-core_2.10-0.8.10.jar:0.8.10]
	at dispatch.classic.Http.apply(Http.scala:21) ~[dispatch-http_2.10-0.8.10.jar:0.8.10]
	at com.mentor.portal.supplier.digikey.DkOauthProvider$.httpRes(DkOauthProvider.scala:117) ~[DkOauthProvider$.class:na]
	at com.mentor.portal.supplier.digikey.DkOauthProvider.callback(DkOauthProvider.scala:48) ~[DkOauthProvider.class:na]
	at omniauth.view.Omniauth$$anonfun$doAuthCallback$2.apply(Omniauth.scala:56) ~[omniauth_2.5_2.10-0.15.jar:0.15]
	at omniauth.view.Omniauth$$anonfun$doAuthCallback$2.apply(Omniauth.scala:53) ~[omniauth_2.5_2.10-0.15.jar:0.15]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library-2.10.4.jar:na]
	at omniauth.view.Omniauth.doAuthCallback(Omniauth.scala:53) ~[omniauth_2.5_2.10-0.15.jar:0.15]
	at omniauth.view.Omniauth$$anonfun$dispatch$1$$anonfun$applyOrElse$2.apply(Omniauth.scala:28) ~[omniauth_2.5_2.10-0.15.jar:0.15]
	at omniauth.view.Omniauth$$anonfun$dispatch$1$$anonfun$applyOrElse$2.apply(Omniauth.scala:28) ~[omniauth_2.5_2.10-0.15.jar:0.15]
	at net.liftweb.http.Templates$$anonfun$lookForClasses$1$$anonfun$apply$11.apply(Templates.scala:275) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.Templates$$anonfun$lookForClasses$1$$anonfun$apply$11.apply(Templates.scala:272) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.common.Full.flatMap(Box.scala:555) ~[lift-common_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.Templates$$anonfun$lookForClasses$1.apply(Templates.scala:271) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.Templates$$anonfun$lookForClasses$1.apply(Templates.scala:269) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55) ~[scala-library-2.10.4.jar:na]
	at scala.collection.immutable.Stream.flatMap(Stream.scala:446) ~[scala-library-2.10.4.jar:na]
	at net.liftweb.util.ListHelpers$class.first(ListHelpers.scala:137) ~[lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.Helpers$.first(Helpers.scala:34) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.Templates$.lookForClasses(Templates.scala:268) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.Templates$.findRawTemplate(Templates.scala:253) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.Templates$.apply(Templates.scala:85) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftSession.net$liftweb$http$LiftSession$$findVisibleTemplate(LiftSession.scala:1367) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftSession$$anonfun$processTemplate$1$$anonfun$apply$43.apply(LiftSession.scala:1119) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftSession$$anonfun$processTemplate$1$$anonfun$apply$43.apply(LiftSession.scala:1119) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.common.EmptyBox.or(Box.scala:646) ~[lift-common_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftSession$$anonfun$processTemplate$1.apply(LiftSession.scala:1119) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftSession$$anonfun$processTemplate$1.apply(LiftSession.scala:1119) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.AnyVarTrait$class.doWith(AnyVar.scala:233) ~[lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.AnyVar.doWith(AnyVar.scala:89) ~[lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftSession.processTemplate(LiftSession.scala:1118) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftSession$$anonfun$27$$anonfun$apply$46$$anonfun$apply$47$$anonfun$apply$50.apply(LiftSession.scala:1229) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftSession$$anonfun$27$$anonfun$apply$46$$anonfun$apply$47$$anonfun$apply$50.apply(LiftSession.scala:1229) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.common.EmptyBox.or(Box.scala:646) ~[lift-common_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftSession$$anonfun$27$$anonfun$apply$46$$anonfun$apply$47.apply(LiftSession.scala:1228) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftSession$$anonfun$27$$anonfun$apply$46$$anonfun$apply$47.apply(LiftSession.scala:1228) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.StackableMaker$class.doWith(Maker.scala:141) ~[lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.Factory$FactoryMaker.doWith(Factory.scala:37) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.StackableMaker$class.doWith(Maker.scala:135) ~[lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.Factory$FactoryMaker.doWith(Factory.scala:37) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftSession$$anonfun$27$$anonfun$apply$46.apply(LiftSession.scala:1227) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftSession$$anonfun$27$$anonfun$apply$46.apply(LiftSession.scala:1223) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftSession.net$liftweb$http$LiftSession$$checkStatelessInSiteMap(LiftSession.scala:1167) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftSession$$anonfun$27.apply(LiftSession.scala:1223) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftSession$$anonfun$27.apply(LiftSession.scala:1221) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.common.EmptyBox.or(Box.scala:646) ~[lift-common_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftSession.processRequest(LiftSession.scala:1221) ~[lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftServlet.net$liftweb$http$LiftServlet$$dispatchStatefulRequest(LiftServlet.scala:423) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftServlet$$anonfun$doSession$1$1.apply(LiftServlet.scala:301) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftServlet$$anonfun$doSession$1$1.apply(LiftServlet.scala:301) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$class.net$liftweb$http$S$$wrapQuery(S.scala:1460) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_nest2InnerInit$1$$anonfun$apply$37.apply(S.scala:1625) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$class.net$liftweb$http$S$$doAround(S.scala:1389) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_nest2InnerInit$1.apply(S.scala:1623) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$class.net$liftweb$http$S$$_nest2InnerInit(S.scala:1622) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42$$anonfun$apply$43$$anonfun$apply$44.apply(S.scala:1666) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$$anonfun$withReq$1.apply(S.scala:1676) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$class.withReq(S.scala:1675) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$.withReq(S.scala:47) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42$$anonfun$apply$43.apply(S.scala:1662) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42.apply(S.scala:1660) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41.apply(S.scala:1659) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1.apply(S.scala:1658) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$class.net$liftweb$http$S$$_innerInit(S.scala:1657) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49$$anonfun$apply$50$$anonfun$apply$51.apply(S.scala:1699) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49$$anonfun$apply$50.apply(S.scala:1697) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:613) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.RequestVarHandler$.apply(Vars.scala:515) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49.apply(S.scala:1696) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:613) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.TransientRequestVarHandler$.apply(Vars.scala:528) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48.apply(S.scala:1695) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47.apply(S.scala:1694) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1.apply(S.scala:1693) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$class.net$liftweb$http$S$$_init(S.scala:1692) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$class.init(S.scala:1274) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.S$.init(S.scala:47) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftServlet.doSession$1(LiftServlet.scala:300) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftServlet.doService(LiftServlet.scala:310) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftServlet$$anonfun$doIt$1$1.apply(LiftServlet.scala:148) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftServlet$$anonfun$doIt$1$1.apply(LiftServlet.scala:147) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.TimeHelpers$class.calcTime(TimeHelpers.scala:345) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.Helpers$.calcTime(Helpers.scala:34) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.TimeHelpers$class.logTime(TimeHelpers.scala:364) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.Helpers$.logTime(Helpers.scala:34) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftServlet.doIt$1(LiftServlet.scala:147) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftServlet.service(LiftServlet.scala:158) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(HTTPProvider.scala:72) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(HTTPProvider.scala:71) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(HTTPProvider.scala:71) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.URLRewriter$.doWith(Req.scala:1278) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1.apply$mcV$sp(HTTPProvider.scala:70) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1.apply(HTTPProvider.scala:70) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2$$anonfun$apply$mcV$sp$1.apply(HTTPProvider.scala:70) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2.apply$mcV$sp(HTTPProvider.scala:66) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2.apply(HTTPProvider.scala:60) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.HTTPProvider$$anonfun$service$2.apply(HTTPProvider.scala:60) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.HTTPProvider$class.service(HTTPProvider.scala:60) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftFilter.service(LiftServlet.scala:928) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(ServletFilterProvider.scala:82) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(ServletFilterProvider.scala:82) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(ServletFilterProvider.scala:82) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.servlet.ServletFilterProvider$class.handleLoan$1(ServletFilterProvider.scala:59) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.servlet.ServletFilterProvider$class.net$liftweb$http$provider$servlet$ServletFilterProvider$$handleLoanWrappers(ServletFilterProvider.scala:63) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ServletFilterProvider.scala:82) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1.apply(ServletFilterProvider.scala:77) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1$$anonfun$apply$mcV$sp$1.apply(ServletFilterProvider.scala:77) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$14$$anonfun$apply$15$$anonfun$apply$16$$anonfun$apply$17.apply(Vars.scala:619) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$14$$anonfun$apply$15$$anonfun$apply$16.apply(Vars.scala:618) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$14$$anonfun$apply$15.apply(Vars.scala:617) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$14.apply(Vars.scala:616) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:615) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.RequestVarHandler$.apply(Vars.scala:515) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1.apply$mcV$sp(ServletFilterProvider.scala:75) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1.apply(ServletFilterProvider.scala:75) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.servlet.ServletFilterProvider$$anonfun$doFilter$1.apply(ServletFilterProvider.scala:75) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$14$$anonfun$apply$15$$anonfun$apply$16$$anonfun$apply$17.apply(Vars.scala:619) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$14$$anonfun$apply$15$$anonfun$apply$16.apply(Vars.scala:618) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$14$$anonfun$apply$15.apply(Vars.scala:617) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$14.apply(Vars.scala:616) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71) [lift-util_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:615) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.TransientRequestVarHandler$.apply(Vars.scala:528) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.provider.servlet.ServletFilterProvider$class.doFilter(ServletFilterProvider.scala:74) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at net.liftweb.http.LiftFilter.doFilter(LiftServlet.scala:928) [lift-webkit_2.10-2.5.1.jar:2.5.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [catalina.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.47]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.47]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.47]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:7.0.47]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.47]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100) [catalina.jar:7.0.47]
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:680) [catalina.jar:7.0.47]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) [catalina.jar:7.0.47]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.47]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.47]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041) [tomcat-coyote.jar:7.0.47]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603) [tomcat-coyote.jar:7.0.47]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) [tomcat-coyote.jar:7.0.47]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_51]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]
INF: [console logger] dispatch: auth.digikey.com POST /o/oauth/token HTTP/1.1
```

**Comment by joescii** [comment]
Resolved in [0.17](https://github.com/ghostm/lift-omniauth/releases/tag/0.17)
